name: weave
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - cdsapi
  - numpy
  - pandas
  - netcdf4
  - xarray
  - dask
  - matplotlib
  - seaborn
  - cartopy
  - plotly
  - nbformat
  - jupyterlab-plotly
  - anywidget

#importlib? pathlib? socket?

# Install anywidget jupyter extension