name: weave
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - cdsapi
  - numpy
  - pandas
  - netcdf4
  - xarray
  - matplotlib
  - seaborn
  - cartopy
  - plotly
  - nbformat
  - jupyterlab-plotly

#importlib? pathlib? socket?

# Install anywidget jupyter extension